name: 'Structurizr'
description: 'Use Structurizr CLI'
inputs:
  args:
    description: 'Arguments for Structurizr CLI'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
