name: 'Structurizr CLI'
description: >
  Call Structurizr CLI with the arguments passed as inputs to the action.

inputs:
  args:
    description: 'Arguments for Structurizr CLI'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'docker://gilbertotcc/structurizr:v1.9.0'
  args:
    - ${{ inputs.args }}
